### ISSUE TITLE
Bug when submitting code with division /

### ISSUE THREAD

**Issue by rodrigoduranna** [acos-server/acos-jsparsons-generator#1]
The parser is breaking the command when faced with a / token in the program

Example: avg = total_sum/num

produces 

avg = total_sum
um

Parson's tokens

**Comment by markkuriekkinen** [comment]
The bug is not in the generator, but in the acos-jsparsons-python-custom app that is used to preview the exercise. (It reads the exercise from the URL since it is encoded in the query parameters.) There is a broken line of code that removes the division operator if it is followed by the character n. Using whitespace around the operator avoids the issue.

**Comment by markkuriekkinen** [comment]
Resolved by https://github.com/acos-server/acos-jsparsons-python-custom/pull/2
Closing now.
